apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesClusterNodePool
metadata:
  labels:
    environment-name: "{{ .Values.env }}"
  name: "np-{{ .Values.env }}-win"
spec:
  forProvider:
    kubernetesClusterIdSelector:
      matchLabels:
        environment-name: "{{ .Values.env }}"
    osType: Windows
    osSku: Windows2022
    nodeCount: 1
    tags:
      Environment: "{{ .Values.env }}"
    vmSize: Standard_DS2_v2
