apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesCluster
metadata:
  labels:
    environment-name: "{{ .Values.env }}"
  name: "aks-{{ .Values.env }}"
spec:
  forProvider:
    networkProfile:
      - networkPlugin: azure
        networkPluginMode: Overlay
        podCidr: 192.168.0.0/16
    defaultNodePool:
      - name: default
        nodeCount: 1
        vmSize: Standard_D2_v2
        enableAutoScaling: false
    dnsPrefix: "{{ .Values.env }}aks1"
    identity:
      - type: SystemAssigned
    location: West Europe
    resourceGroupNameRef:
      name: "{{ .Values.env }}-rg"
    tags:
      Environment: "{{ .Values.env }}"
